
package com.siebel.ordermanagement.quote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QuoteWebService", targetNamespace = "http://siebel.com/OrderManagement/Quote", wsdlLocation = "http://localhost/wsdl/QuoteWebService.wsdl")
public class QuoteWebService
    extends Service
{

    private final static URL QUOTEWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/QuoteWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        QUOTEWEBSERVICE_WSDL_LOCATION = url;
    }

    public QuoteWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteWebService() {
        super(QUOTEWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/Quote", "QuoteWebService"));
    }

    /**
     * 
     * @return
     *     returns QuoteItemPort
     */
    @WebEndpoint(name = "QuoteItemPort")
    public QuoteItemPort getQuoteItemPort() {
        return (QuoteItemPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote", "QuoteItemPort"), QuoteItemPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteItemPort
     */
    @WebEndpoint(name = "QuoteItemPort")
    public QuoteItemPort getQuoteItemPort(WebServiceFeature... features) {
        return (QuoteItemPort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote", "QuoteItemPort"), QuoteItemPort.class, features);
    }

    /**
     * 
     * @return
     *     returns QuotePort
     */
    @WebEndpoint(name = "QuotePort")
    public QuotePort getQuotePort() {
        return (QuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote", "QuotePort"), QuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuotePort
     */
    @WebEndpoint(name = "QuotePort")
    public QuotePort getQuotePort(WebServiceFeature... features) {
        return (QuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/Quote", "QuotePort"), QuotePort.class, features);
    }

}
