
package com.siebel.ordermanagement.quote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QuotePort", targetNamespace = "http://siebel.com/OrderManagement/Quote")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.item.data.ObjectFactory.class,
    com.siebel.ordermanagement.quote.ObjectFactory.class,
    com.siebel.ordermanagement.quote.data.ObjectFactory.class
})
public interface QuotePort {


    /**
     * 
     * @param deleteQuoteInput
     * @return
     *     returns com.siebel.ordermanagement.quote.DeleteQuoteOutput
     */
    @WebMethod(operationName = "DeleteQuote", action = "document/http://siebel.com/OrderManagement/Quote:DeleteQuote")
    @WebResult(name = "DeleteQuote_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "DeleteQuote_Output")
    public DeleteQuoteOutput deleteQuote(
        @WebParam(name = "DeleteQuote_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "DeleteQuote_Input")
        DeleteQuoteInput deleteQuoteInput);

    /**
     * 
     * @param getQuoteByIdInput
     * @return
     *     returns com.siebel.ordermanagement.quote.GetQuoteByIdOutput
     */
    @WebMethod(operationName = "GetQuoteById", action = "document/http://siebel.com/OrderManagement/Quote:GetQuoteById")
    @WebResult(name = "GetQuoteById_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteById_Output")
    public GetQuoteByIdOutput getQuoteById(
        @WebParam(name = "GetQuoteById_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteById_Input")
        GetQuoteByIdInput getQuoteByIdInput);

    /**
     * 
     * @param getQuoteInput
     * @return
     *     returns com.siebel.ordermanagement.quote.GetQuoteOutput
     */
    @WebMethod(operationName = "GetQuote", action = "document/http://siebel.com/OrderManagement/Quote:GetQuote")
    @WebResult(name = "GetQuote_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuote_Output")
    public GetQuoteOutput getQuote(
        @WebParam(name = "GetQuote_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuote_Input")
        GetQuoteInput getQuoteInput);

    /**
     * 
     * @param synchronizeQuoteInput
     * @return
     *     returns com.siebel.ordermanagement.quote.SynchronizeQuoteOutput
     */
    @WebMethod(operationName = "SynchronizeQuote", action = "document/http://siebel.com/OrderManagement/Quote:SynchronizeQuote")
    @WebResult(name = "SynchronizeQuote_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "SynchronizeQuote_Output")
    public SynchronizeQuoteOutput synchronizeQuote(
        @WebParam(name = "SynchronizeQuote_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "SynchronizeQuote_Input")
        SynchronizeQuoteInput synchronizeQuoteInput);

    /**
     * 
     * @param insertQuoteInput
     * @return
     *     returns com.siebel.ordermanagement.quote.InsertQuoteOutput
     */
    @WebMethod(operationName = "InsertQuote", action = "document/http://siebel.com/OrderManagement/Quote:InsertQuote")
    @WebResult(name = "InsertQuote_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "InsertQuote_Output")
    public InsertQuoteOutput insertQuote(
        @WebParam(name = "InsertQuote_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "InsertQuote_Input")
        InsertQuoteInput insertQuoteInput);

    /**
     * 
     * @param updateQuoteInput
     * @return
     *     returns com.siebel.ordermanagement.quote.UpdateQuoteOutput
     */
    @WebMethod(operationName = "UpdateQuote", action = "document/http://siebel.com/OrderManagement/Quote:UpdateQuote")
    @WebResult(name = "UpdateQuote_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "UpdateQuote_Output")
    public UpdateQuoteOutput updateQuote(
        @WebParam(name = "UpdateQuote_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "UpdateQuote_Input")
        UpdateQuoteInput updateQuoteInput);

}
