
package com.siebel.ordermanagement.quote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QuoteItemPort", targetNamespace = "http://siebel.com/OrderManagement/Quote")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.ordermanagement.quote.ObjectFactory.class,
    com.siebel.ordermanagement.quote.data.ObjectFactory.class,
    com.siebel.ordermanagement.quote.item.data.ObjectFactory.class
})
public interface QuoteItemPort {


    /**
     * 
     * @param getQuoteItemByIdInput
     * @return
     *     returns com.siebel.ordermanagement.quote.GetQuoteItemByIdOutput
     */
    @WebMethod(operationName = "GetQuoteItemById", action = "document/http://siebel.com/OrderManagement/Quote:GetQuoteItemById")
    @WebResult(name = "GetQuoteItemById_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteItemById_Output")
    public GetQuoteItemByIdOutput getQuoteItemById(
        @WebParam(name = "GetQuoteItemById_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteItemById_Input")
        GetQuoteItemByIdInput getQuoteItemByIdInput);

    /**
     * 
     * @param insertQuoteItemInput
     * @return
     *     returns com.siebel.ordermanagement.quote.InsertQuoteItemOutput
     */
    @WebMethod(operationName = "InsertQuoteItem", action = "document/http://siebel.com/OrderManagement/Quote:InsertQuoteItem")
    @WebResult(name = "InsertQuoteItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "InsertQuoteItem_Output")
    public InsertQuoteItemOutput insertQuoteItem(
        @WebParam(name = "InsertQuoteItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "InsertQuoteItem_Input")
        InsertQuoteItemInput insertQuoteItemInput);

    /**
     * 
     * @param getQuoteItemInput
     * @return
     *     returns com.siebel.ordermanagement.quote.GetQuoteItemOutput
     */
    @WebMethod(operationName = "GetQuoteItem", action = "document/http://siebel.com/OrderManagement/Quote:GetQuoteItem")
    @WebResult(name = "GetQuoteItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteItem_Output")
    public GetQuoteItemOutput getQuoteItem(
        @WebParam(name = "GetQuoteItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "GetQuoteItem_Input")
        GetQuoteItemInput getQuoteItemInput);

    /**
     * 
     * @param synchronizeQuoteItemInput
     * @return
     *     returns com.siebel.ordermanagement.quote.SynchronizeQuoteItemOutput
     */
    @WebMethod(operationName = "SynchronizeQuoteItem", action = "document/http://siebel.com/OrderManagement/Quote:SynchronizeQuoteItem")
    @WebResult(name = "SynchronizeQuoteItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "SynchronizeQuoteItem_Output")
    public SynchronizeQuoteItemOutput synchronizeQuoteItem(
        @WebParam(name = "SynchronizeQuoteItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "SynchronizeQuoteItem_Input")
        SynchronizeQuoteItemInput synchronizeQuoteItemInput);

    /**
     * 
     * @param updateQuoteItemInput
     * @return
     *     returns com.siebel.ordermanagement.quote.UpdateQuoteItemOutput
     */
    @WebMethod(operationName = "UpdateQuoteItem", action = "document/http://siebel.com/OrderManagement/Quote:UpdateQuoteItem")
    @WebResult(name = "UpdateQuoteItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "UpdateQuoteItem_Output")
    public UpdateQuoteItemOutput updateQuoteItem(
        @WebParam(name = "UpdateQuoteItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "UpdateQuoteItem_Input")
        UpdateQuoteItemInput updateQuoteItemInput);

    /**
     * 
     * @param deleteQuoteItemInput
     * @return
     *     returns com.siebel.ordermanagement.quote.DeleteQuoteItemOutput
     */
    @WebMethod(operationName = "DeleteQuoteItem", action = "document/http://siebel.com/OrderManagement/Quote:DeleteQuoteItem")
    @WebResult(name = "DeleteQuoteItem_Output", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "DeleteQuoteItem_Output")
    public DeleteQuoteItemOutput deleteQuoteItem(
        @WebParam(name = "DeleteQuoteItem_Input", targetNamespace = "http://siebel.com/OrderManagement/Quote", partName = "DeleteQuoteItem_Input")
        DeleteQuoteItemInput deleteQuoteItemInput);

}
