
package com.siebel.ordermanagement.abo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ABOWebService", targetNamespace = "http://siebel.com/OrderManagement/ABO", wsdlLocation = "http://localhost/wsdl/ABOWebService.wsdl")
public class ABOWebService
    extends Service
{

    private final static URL ABOWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/wsdl/ABOWebService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ABOWEBSERVICE_WSDL_LOCATION = url;
    }

    public ABOWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ABOWebService() {
        super(ABOWEBSERVICE_WSDL_LOCATION, new QName("http://siebel.com/OrderManagement/ABO", "ABOWebService"));
    }

    /**
     * 
     * @return
     *     returns SuspendAssetToQuotePort
     */
    @WebEndpoint(name = "SuspendAssetToQuotePort")
    public SuspendAssetToQuotePort getSuspendAssetToQuotePort() {
        return (SuspendAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SuspendAssetToQuotePort"), SuspendAssetToQuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuspendAssetToQuotePort
     */
    @WebEndpoint(name = "SuspendAssetToQuotePort")
    public SuspendAssetToQuotePort getSuspendAssetToQuotePort(WebServiceFeature... features) {
        return (SuspendAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SuspendAssetToQuotePort"), SuspendAssetToQuotePort.class, features);
    }

    /**
     * 
     * @return
     *     returns ModifyAssetToOrderPort
     */
    @WebEndpoint(name = "ModifyAssetToOrderPort")
    public ModifyAssetToOrderPort getModifyAssetToOrderPort() {
        return (ModifyAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ModifyAssetToOrderPort"), ModifyAssetToOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyAssetToOrderPort
     */
    @WebEndpoint(name = "ModifyAssetToOrderPort")
    public ModifyAssetToOrderPort getModifyAssetToOrderPort(WebServiceFeature... features) {
        return (ModifyAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ModifyAssetToOrderPort"), ModifyAssetToOrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns AutoAssetPort
     */
    @WebEndpoint(name = "AutoAssetPort")
    public AutoAssetPort getAutoAssetPort() {
        return (AutoAssetPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "AutoAssetPort"), AutoAssetPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoAssetPort
     */
    @WebEndpoint(name = "AutoAssetPort")
    public AutoAssetPort getAutoAssetPort(WebServiceFeature... features) {
        return (AutoAssetPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "AutoAssetPort"), AutoAssetPort.class, features);
    }

    /**
     * 
     * @return
     *     returns SuspendAssetToOrderPort
     */
    @WebEndpoint(name = "SuspendAssetToOrderPort")
    public SuspendAssetToOrderPort getSuspendAssetToOrderPort() {
        return (SuspendAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SuspendAssetToOrderPort"), SuspendAssetToOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuspendAssetToOrderPort
     */
    @WebEndpoint(name = "SuspendAssetToOrderPort")
    public SuspendAssetToOrderPort getSuspendAssetToOrderPort(WebServiceFeature... features) {
        return (SuspendAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SuspendAssetToOrderPort"), SuspendAssetToOrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns ResumeAssetToQuotePort
     */
    @WebEndpoint(name = "ResumeAssetToQuotePort")
    public ResumeAssetToQuotePort getResumeAssetToQuotePort() {
        return (ResumeAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ResumeAssetToQuotePort"), ResumeAssetToQuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResumeAssetToQuotePort
     */
    @WebEndpoint(name = "ResumeAssetToQuotePort")
    public ResumeAssetToQuotePort getResumeAssetToQuotePort(WebServiceFeature... features) {
        return (ResumeAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ResumeAssetToQuotePort"), ResumeAssetToQuotePort.class, features);
    }

    /**
     * 
     * @return
     *     returns SubmitOrderPort
     */
    @WebEndpoint(name = "SubmitOrderPort")
    public SubmitOrderPort getSubmitOrderPort() {
        return (SubmitOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SubmitOrderPort"), SubmitOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubmitOrderPort
     */
    @WebEndpoint(name = "SubmitOrderPort")
    public SubmitOrderPort getSubmitOrderPort(WebServiceFeature... features) {
        return (SubmitOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "SubmitOrderPort"), SubmitOrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns ResumeAssetToOrderPort
     */
    @WebEndpoint(name = "ResumeAssetToOrderPort")
    public ResumeAssetToOrderPort getResumeAssetToOrderPort() {
        return (ResumeAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ResumeAssetToOrderPort"), ResumeAssetToOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResumeAssetToOrderPort
     */
    @WebEndpoint(name = "ResumeAssetToOrderPort")
    public ResumeAssetToOrderPort getResumeAssetToOrderPort(WebServiceFeature... features) {
        return (ResumeAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ResumeAssetToOrderPort"), ResumeAssetToOrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns DisconnectAssetToQuotePort
     */
    @WebEndpoint(name = "DisconnectAssetToQuotePort")
    public DisconnectAssetToQuotePort getDisconnectAssetToQuotePort() {
        return (DisconnectAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "DisconnectAssetToQuotePort"), DisconnectAssetToQuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisconnectAssetToQuotePort
     */
    @WebEndpoint(name = "DisconnectAssetToQuotePort")
    public DisconnectAssetToQuotePort getDisconnectAssetToQuotePort(WebServiceFeature... features) {
        return (DisconnectAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "DisconnectAssetToQuotePort"), DisconnectAssetToQuotePort.class, features);
    }

    /**
     * 
     * @return
     *     returns ModifyAssetToQuotePort
     */
    @WebEndpoint(name = "ModifyAssetToQuotePort")
    public ModifyAssetToQuotePort getModifyAssetToQuotePort() {
        return (ModifyAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ModifyAssetToQuotePort"), ModifyAssetToQuotePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyAssetToQuotePort
     */
    @WebEndpoint(name = "ModifyAssetToQuotePort")
    public ModifyAssetToQuotePort getModifyAssetToQuotePort(WebServiceFeature... features) {
        return (ModifyAssetToQuotePort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "ModifyAssetToQuotePort"), ModifyAssetToQuotePort.class, features);
    }

    /**
     * 
     * @return
     *     returns DisconnectAssetToOrderPort
     */
    @WebEndpoint(name = "DisconnectAssetToOrderPort")
    public DisconnectAssetToOrderPort getDisconnectAssetToOrderPort() {
        return (DisconnectAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "DisconnectAssetToOrderPort"), DisconnectAssetToOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisconnectAssetToOrderPort
     */
    @WebEndpoint(name = "DisconnectAssetToOrderPort")
    public DisconnectAssetToOrderPort getDisconnectAssetToOrderPort(WebServiceFeature... features) {
        return (DisconnectAssetToOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "DisconnectAssetToOrderPort"), DisconnectAssetToOrderPort.class, features);
    }

    /**
     * 
     * @return
     *     returns AutoOrderPort
     */
    @WebEndpoint(name = "AutoOrderPort")
    public AutoOrderPort getAutoOrderPort() {
        return (AutoOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "AutoOrderPort"), AutoOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoOrderPort
     */
    @WebEndpoint(name = "AutoOrderPort")
    public AutoOrderPort getAutoOrderPort(WebServiceFeature... features) {
        return (AutoOrderPort)super.getPort(new QName("http://siebel.com/OrderManagement/ABO", "AutoOrderPort"), AutoOrderPort.class, features);
    }

}
