
package com.siebel.xml.sessionaccess;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "port", targetNamespace = "http://www.siebel.com/xml/SessionAccess")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Port {


    /**
     * 
     * @param sessionAccessGetProfileAttrInput
     * @return
     *     returns com.siebel.xml.sessionaccess.SessionAccessGetProfileAttrOutput
     */
    @WebMethod(operationName = "SessionAccessGetProfileAttr", action = "document/http://www.siebel.com/xml/SessionAccess:SessionAccessGetProfileAttr")
    @WebResult(name = "SessionAccessGetProfileAttr_Output", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessGetProfileAttr_Output")
    public SessionAccessGetProfileAttrOutput sessionAccessGetProfileAttr(
        @WebParam(name = "SessionAccessGetProfileAttr_Input", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessGetProfileAttr_Input")
        SessionAccessGetProfileAttrInput sessionAccessGetProfileAttrInput);

    /**
     * 
     * @param sessionAccessEchoInput
     * @return
     *     returns com.siebel.xml.sessionaccess.SessionAccessEchoOutput
     */
    @WebMethod(operationName = "SessionAccessEcho", action = "document/http://www.siebel.com/xml/SessionAccess:SessionAccessEcho")
    @WebResult(name = "SessionAccessEcho_Output", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessEcho_Output")
    public SessionAccessEchoOutput sessionAccessEcho(
        @WebParam(name = "SessionAccessEcho_Input", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessEcho_Input")
        SessionAccessEchoInput sessionAccessEchoInput);

    /**
     * 
     * @param sessionAccessSetProfileAttrInput
     */
    @WebMethod(operationName = "SessionAccessSetProfileAttr", action = "document/http://www.siebel.com/xml/SessionAccess:SessionAccessSetProfileAttr")
    @Oneway
    public void sessionAccessSetProfileAttr(
        @WebParam(name = "SessionAccessSetProfileAttr_Input", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessSetProfileAttr_Input")
        SessionAccessSetProfileAttrInput sessionAccessSetProfileAttrInput);

    /**
     * 
     * @param sessionAccessPingInput
     * @return
     *     returns com.siebel.xml.sessionaccess.SessionAccessPingOutput
     */
    @WebMethod(operationName = "SessionAccessPing", action = "document/http://www.siebel.com/xml/SessionAccess:SessionAccessPing")
    @WebResult(name = "SessionAccessPing_Output", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessPing_Output")
    public SessionAccessPingOutput sessionAccessPing(
        @WebParam(name = "SessionAccessPing_Input", targetNamespace = "http://www.siebel.com/xml/SessionAccess", partName = "SessionAccessPing_Input")
        SessionAccessPingInput sessionAccessPingInput);

}
